name: gdsc_lessons
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.9.2







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_logo.png"
  image_path_ios: "assets/images/launcher_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/launcher_logo.png"
  remove_alpha_ios: true 
  
  
  
  
  flutter_lints: ^5.0.0





flutter:

  assets:
  - assets/images/launcher_logo.png
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
